### ISSUE TITLE
Error in reading/converting/stacking a czi file

### ISSUE THREAD

**Issue by jimmymcheung** [SFB-ELAINE/readCzi#1]
When trying to execute (any of) the command of readCzi, an error message is occurred: _The number of channels does not correspond to the number of channel names in the metadata._

I know it might due to the problem of the metadata of the file. But I have absolute no issue when opening with Zen2 software. I tried to read the metadata using the `readCziMetadata()`function but it returns the same error message. 

I looked into metadata, and under the channel information sections, it shows: 
`        <Dimensions>
          <Channels>
            <Channel Id="Channel:0">
              <Color>#FFFFFFFF</Color>
              <Fluor>62 HE BFP / GFP / HcRed</Fluor>
              <AcquisitionMode>WideField</AcquisitionMode>
              <ExposureTime>1172250000</ExposureTime>
              <Reflector>62 HE BFP / GFP / HcRed</Reflector>
              <NACondenser>0.1021</NACondenser>
              <IlluminationType>Epifluorescence</IlluminationType>
              <ContrastMethod>Fluorescence</ContrastMethod>
              <PixelType>Bgr48</PixelType>
              <ComponentBitCount>12</ComponentBitCount>
              <DetectorSettings>
                <Binning>1,1</Binning>
                <Detector Id="Detector:AxioCam MRc5" />
              </DetectorSettings>
              <LightSourcesSettings>
                <LightSourceSettings>
                  <Intensity>25.42 %</Intensity>
                  <LightSource Id="LightSource:1" />
                </LightSourceSettings>
              </LightSourcesSettings>
              <FilterSetRef Id="FilterSet:1" />
            </Channel>
          </Channels>
          <T>
            <StartTime>0001-01-01T00:00:00</StartTime>
          </T>
        </Dimensions>`

The only channel appears to be numbered as 0, which might be the cause of the problem. but is there a way to edit the channel info?

**Comment by buddekai** [comment]
Hi,
sorry for not responding earlier. Would your send me a sample czi file which the package failed to convert (either a link to a download site or, if it's small enough, to my university email address. You'll find it here: https://mosi.informatik.uni-rostock.de/en/group/staff/kai-budde/. I'll be working on it ASAP.
Thanks,
Kai

**Comment by buddekai** [comment]
I've fixed a few bugs. Please check your files with version 0.1.11. It worked for me! Please let me know if it works for you as well. (The scale bar you've probably entered in the ZEN software is not being converted to a tif. If you need scale bars to be automatically drawn in your tifs, I could easily add a function.)

**Comment by jimmymcheung** [comment]
sorry for late reply, I didn't check my github. It can open and convert the .czi file now! Thanks a lot for that!

and reply's to your last comment: yes it would be grateful to also have the option to include that scale bar, since it would also be important to know the actual size mapped.

**Comment by buddekai** [comment]
possibility to draw scale bar is now included

**Comment by jimmymcheung** [comment]
Thanks!!
